psql acb1          < acb1          
psql ap-daxti      < ap-daxti      
psql app19         < app19         
psql apprueba      < apprueba      
psql apra19prueba  < apra19prueba  
psql apracomsa     < apracomsa     
psql apracomsa19   < apracomsa19   
psql atver         < atver         
psql atver19       < atver19       
psql avisusa       < avisusa       
psql bc-daxti      < bc-daxti      
psql bc19test      < bc19test      
psql bcprueba      < bcprueba      
psql biolitsa      < biolitsa      
psql biomicro19    < biomicro19    
psql blutec        < blutec        
psql blutec19      < blutec19      
psql bu_prueba     < bu_prueba     
psql busi12        < busi12        
psql busicentury   < busicentury   
psql busicentury19 < busicentury19 
psql catver        < catver        
psql catver19      < catver19      
psql catver_prueba < catver_prueba 
psql dbenblaco     < dbenblaco     
psql dbmychart     < dbmychart     
psql dbname        < dbname        
psql gambalit      < gambalit      
psql langolit      < langolit      
psql peru326       < peru326       
psql ponte19       < ponte19       
psql probol19      < probol19      
psql propar19      < propar19      
psql prueba327     < prueba327     
psql qualperu19    < qualperu19    
psql tradetecsa    < tradetecsa    
psql tradetecsa19  < tradetecsa19  

