db_array=(
    https://www.mixcloud.com/ministeriotiempodevictoria/esta-vivo-el-modelo-lutero-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/esta-vivo-el-modelo-lutero-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/habr%C3%A1-alguno-como-dios/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-origen-de-tus-conflictos-11/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-valor-de-la-segunda-generacion-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-valor-de-la-segunda-generacion-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/requisitos-para-la-victoria/
    https://www.mixcloud.com/ministeriotiempodevictoria/como-s%C3%A9-si-soy-salvo/
    https://www.mixcloud.com/ministeriotiempodevictoria/como-se-si-soy-salvo-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-origen-de-tus-conflictos-12/
    https://www.mixcloud.com/ministeriotiempodevictoria/cuando-una-naci%C3%B3n-est%C3%A1-en-guerra-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/cuando-una-naci%C3%B3n-est%C3%A1-en-guerra-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/qu%C3%A9-necesita-tu-alma/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-familia-llamada-iglesia-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-familia-llamada-iglesia-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-origen-de-tus-conflictos-13/
    https://www.mixcloud.com/ministeriotiempodevictoria/considerando-nuestra-identidad-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/considerando-nuestra-identidad-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-vez-mas-jezabel/
    https://www.mixcloud.com/ministeriotiempodevictoria/cimentando-una-nueva-generacion-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/cimentando-una-nueva-generacion-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-origen-de-tus-conflictos-14/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-obediencia-de-lo-inmediato/
    https://www.mixcloud.com/ministeriotiempodevictoria/se%C3%B1or-quiero-tu-presencia/
    https://www.mixcloud.com/ministeriotiempodevictoria/ha-desaparecido-el-legalismo-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/ha-desaparecido-el-legalismo-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/un-viejo-y-conocido-enemigo/
    https://www.mixcloud.com/ministeriotiempodevictoria/que-herencia-dejaremos-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/que-herencia-dejaremos-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/solo-las-cosas-imposibles/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-significado-de-las-parabolas-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-significado-de-las-parabolas-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/como-se-lo-que-dios-quiere/
    https://www.mixcloud.com/ministeriotiempodevictoria/doce-pasos-para-el-exodo-final-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/doce-pasos-para-el-exodo-final-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/pasos-hacia-la-libertad/
    https://www.mixcloud.com/ministeriotiempodevictoria/madurez-una-materia-basica-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/madurez-una-materia-basica-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/un-gran-misterio-revelado/
    https://www.mixcloud.com/ministeriotiempodevictoria/catacumbas-espirituales-siglo-xxi/
    https://www.mixcloud.com/ministeriotiempodevictoria/hay-un-exodo-que-sigue-vigente-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/hay-un-exodo-que-sigue-vigente-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/dios-no-me-escucha/
    https://www.mixcloud.com/ministeriotiempodevictoria/es-cristo-nuestra-vida/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-valiosa-llave-de-autoridad/
    https://www.mixcloud.com/ministeriotiempodevictoria/fotograf%C3%ADa-de-un-remanente/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-mentalidad-de-cambio-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-mentalidad-de-cambio-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/el-divino-mecanismo-de-tu-conciencia/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-verdad-que-no-ha-sido-cancelada-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-verdad-que-no-ha-sido-cancelada-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/simplemente-la-fe/
    https://www.mixcloud.com/ministeriotiempodevictoria/en-verdad-faltan-cuatro-meses-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/en-verdad-faltan-cuatro-meses-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/definiendo-la-iglesia-genuina/
    https://www.mixcloud.com/ministeriotiempodevictoria/parecidos-a-cristo/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-palabra-nunca-muere-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-palabra-nunca-muere-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/segun-el-hombre-piensa/
    https://www.mixcloud.com/ministeriotiempodevictoria/siete-principios-para-cambiar-tu-nombre/
    https://www.mixcloud.com/ministeriotiempodevictoria/cuando-llega-la-noche/
    https://www.mixcloud.com/ministeriotiempodevictoria/liberando-tu-tierra/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-gran-simiente-de-bendici%C3%B3n-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-gran-simiente-de-bendicion-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/encontraste-tu-cobertura/
    https://www.mixcloud.com/ministeriotiempodevictoria/no-son-detalles-menores-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/no-son-detalles-menores-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/cuando-la-ignorancia-es-derrota/
    https://www.mixcloud.com/ministeriotiempodevictoria/en-pos-de-otra-oportunidad-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/en-pos-de-otra-oportunidad-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/la-prueba-de-la-fe/
    https://www.mixcloud.com/ministeriotiempodevictoria/los-enemigos-de-tu-madurez-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/los-enemigos-de-tu-madurez-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/tiempos-de-seriedad/
    https://www.mixcloud.com/ministeriotiempodevictoria/a-que-ciudad-perteneces-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/a-que-ciudad-perteneces-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/como-predicaran-sin-ser-enviados/
    https://www.mixcloud.com/ministeriotiempodevictoria/hora-de-doblar-rodillas/
    https://www.mixcloud.com/ministeriotiempodevictoria/pioneros-de-la-justicia/
    https://www.mixcloud.com/ministeriotiempodevictoria/casa-dividida-no-prevalece-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/casa-dividida-no-prevalece-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-generacion-josue-1/
    https://www.mixcloud.com/ministeriotiempodevictoria/una-generacion-josue-2/
    https://www.mixcloud.com/ministeriotiempodevictoria/aquello-que-nadie-nos-ense%C3%B1o/
    https://www.mixcloud.com/ministeriotiempodevictoria/por-si-fueramos-esparcidos/
    https://www.mixcloud.com/ministeriotiempodevictoria/mientras-llega-el-tiempo-divino/
    https://www.mixcloud.com/ministeriotiempodevictoria/un-remanente-llamado-jacob-1/
)

for i in "${db_array[@]}"; do 
   #echo $i
   youtube-dl -f http $i
done
